version: '2'
services:
  jhlibrarynocache-app:
    image: jhlibrarynocache
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhlibrarynocache-mysql:3306/jhlibrarynocache?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  jhlibrarynocache-mysql:
    extends:
      file: mysql.yml
      service: jhlibrarynocache-mysql
